// Source-visible equipment names plus an authored commercial-gym fixture.
export const equipment = [
  "Ab Wheel",
  "Abductor Machine",
  "Ab Crunch Machine",
  "Adjustable Bench - Decline",
  "Agility Ladder",
  "Adductor Machine",
  "Assisted Chin up / Dips Machine",
  "Ankle Attachment",
  "Barbell",
  "Battle Ropes",
  "BOSU",
  "Bench Adjustable",
  "Dumbbell",
  "Dowel",
  "Elliptical",
  "EZ Bar",
  "Fan Bike",
  "Flat Bar Attachment",
  "Foam Roll",
  "Hack Squat 45 Degree Machine",
  "Hack Squat Machine",
  "Handle Attachment",
  "Hip Thrust Machine",
  "Horizontal Leg Press Machine",
  "Kettlebell",
  "Resistance Band",
  "Treadmill",
  "Wall",
  "Yoga Mat",
  "Cable Machine",
  "Chest Press Machine",
  "Dip Station",
  "Lat Pulldown Machine",
  "Leg Curl Machine",
  "Leg Extension Machine",
  "Medicine Ball",
  "Pec Deck Machine",
  "Pull Up Bar",
  "Rowing Machine",
  "Seated Row Machine",
  "Shoulder Press Machine",
  "Smith Machine",
  "Squat Rack",
  "Stair Climber",
  "Stationary Bike",
  "Stability Ball",
  "Step Platform",
  "Suspension Trainer",
  "Trap Bar",
  "Triceps Rope Attachment",
  "Vertical Leg Press Machine",
  "Weight Plate",
  "Weighted Sled",
  "Workout Bench",
  "Yoga Block",

];

export const commercialGymEquipment = [...equipment];
