"use client";
import Link from 'next/link';
import { useState } from 'react';
import { Check, ChevronLeft } from 'lucide-react';
import { Dialog, ErrorNote, Field, Pending, useCommand, useResource } from './ui';

export type TimeSlot={id:string;workspaceId:string;startsAt:string;endsAt:string;cancelMinutes:number;state:'available'|'withdrawn';reserved:boolean};
export type Appointment={id:string;slotId:string;workspaceId:string;coachName:string;memberName?:string;startsAt:string;endsAt:string;cancelMinutes:number;state:'booked'|'canceled';canCancel:boolean};
export type BookingData={coachName:string|null;slots:TimeSlot[];appointments:Appointment[]};
const dateKey=(value:string,zone:string)=>new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));
const timeLabel=(value:string,zone:string)=>new Date(value).toLocaleTimeString('en-US',{timeZone:zone,hour:'numeric',minute:'2-digit'});
const fullDate=(value:string,zone:string)=>new Date(value).toLocaleString('en-US',{timeZone:zone,dateStyle:'medium',timeStyle:'short'});
export function BookingView({data,zone,back,busy,error,reload,onBook,onCancel}:{data:BookingData;zone:string;back:string;busy:boolean;error?:string;reload:()=>void;onBook:(slot:TimeSlot)=>Promise<boolean>;onCancel:(item:Appointment)=>Promise<boolean>}){
 const [day,setDay]=useState(''),[selected,setSelected]=useState<string|null>(null),[cancel,setCancel]=useState<Appointment|null>(null),[confirmed,setConfirmed]=useState(false);
 const dates=[...new Set(data.slots.filter(s=>s.state==='available'&&!s.reserved).map(s=>dateKey(s.startsAt,zone)))];
 const activeDay=dates.includes(day)?day:dates[0],slots=data.slots.filter(s=>s.state==='available'&&!s.reserved&&dateKey(s.startsAt,zone)===activeDay),chosen=slots.find(s=>s.id===selected);
 return <section className="booking-sheet"><header className="native-titlebar"><Link href={back} className="icon-button" aria-label="Back"><ChevronLeft/></Link><h1>{data.coachName?'Schedule Kickoff Call':'Appointments'}</h1><span/></header>
 {data.coachName&&<><h2>Book your call with {data.coachName}.</h2><p>Choose from your coach’s available times.</p><p className="booking-zone">Times shown in {zone}</p></>}
 <ErrorNote message={error}/>{error&&<button className="button" disabled={busy} onClick={reload}>Refresh Available Times</button>}
 {confirmed&&<p className="booking-confirmed" role="status"><Check size={18}/> Appointment booked. Your saved details appear below.</p>}
 {data.coachName&&<>{dates.length?<><div className="booking-days" role="group" aria-label="Appointment date">{dates.map(date=>{const value=slots.find(s=>dateKey(s.startsAt,zone)===date)||data.slots.find(s=>dateKey(s.startsAt,zone)===date)!;return <button key={date} aria-label={new Date(value.startsAt).toLocaleDateString('en-US',{timeZone:zone,dateStyle:'full'})} disabled={busy} aria-pressed={date===activeDay} onClick={()=>{setDay(date);setSelected(null);setConfirmed(false);}}><span>{new Date(value.startsAt).toLocaleDateString('en-US',{timeZone:zone,weekday:'short'})}</span><strong>{new Date(value.startsAt).toLocaleDateString('en-US',{timeZone:zone,day:'numeric'})}</strong></button>;})}</div><p className="booking-selected-date">{slots[0]&&new Date(slots[0].startsAt).toLocaleDateString('en-US',{timeZone:zone,dateStyle:'full'})}</p><div className="booking-times" role="group" aria-label="Appointment time">{slots.map(slot=><button key={slot.id} disabled={busy} aria-pressed={selected===slot.id} onClick={()=>{setSelected(slot.id);setConfirmed(false);}}>{timeLabel(slot.startsAt,zone)}<span>{Math.round((Date.parse(slot.endsAt)-Date.parse(slot.startsAt))/60000)} min</span></button>)}</div><div className="booking-submit">{chosen&&<p>{fullDate(chosen.startsAt,zone)} · {zone}</p>}{chosen&&<p>Cancel up to {chosen.cancelMinutes?`${chosen.cancelMinutes} minutes before the call`:'the start of the call'}.</p>}<button className="button primary full" disabled={busy||!chosen} onClick={async()=>{if(chosen&&await onBook(chosen)){setConfirmed(true);setSelected(null);}}}>{busy?'Saving…':chosen?`Book ${timeLabel(chosen.startsAt,zone)}`:'Select a time'}</button></div></>:<div className="booking-empty"><h3>No available times</h3><p>Your coach has not published an available time yet.</p><button className="button" onClick={reload}>Refresh Times</button></div>}<Link className="button full" href="/app/settings/support">None of these times work for me</Link></>}
 <section className="booking-upcoming"><h2>Your appointments</h2>{!data.appointments.length&&<p>No appointments booked yet.</p>}{data.appointments.map(item=><article key={item.id}><h3>{item.coachName}</h3><p>{fullDate(item.startsAt,zone)}</p><p>{item.state==='canceled'?'Canceled':`${Math.round((Date.parse(item.endsAt)-Date.parse(item.startsAt))/60000)} minute call`}</p>{item.canCancel&&<button className="button" disabled={busy} onClick={()=>setCancel(item)}>Cancel Appointment</button>}</article>)}</section>
 {cancel&&<Dialog title="Cancel this appointment?" onClose={()=>{if(!busy)setCancel(null);}}><p>{fullDate(cancel.startsAt,zone)} with {cancel.coachName}</p><ErrorNote message={error}/><button className="button primary" disabled={busy} onClick={()=>setCancel(null)}>Keep Appointment</button><button className="button" disabled={busy} onClick={async()=>{if(await onCancel(cancel))setCancel(null);}}>{busy?'Canceling…':'Cancel Appointment'}</button></Dialog>}
 </section>;
}
export function Appointments({workspaceId,zone,query}:{workspaceId?:string;zone:string;query:string}){
 const resource=useResource<BookingData>(workspaceId?`coaches/${workspaceId}/availability`:'me/appointments'),mutation=useCommand();
 if(!resource.data)return <Pending error={resource.error} reload={resource.reload}/>;
 return <BookingView data={resource.data} zone={zone} back={`/app/coaches${query}`} busy={mutation.busy} error={mutation.error||resource.error} reload={resource.reload} onBook={async slot=>{const result=await mutation.run('booking.reserve',{id:slot.id});if(!result)return false;resource.update(data=>({...data,slots:data.slots.filter(s=>s.id!==slot.id),appointments:[...data.appointments,{id:result.id!,slotId:slot.id,workspaceId:slot.workspaceId,coachName:data.coachName||'Your coach',startsAt:slot.startsAt,endsAt:slot.endsAt,cancelMinutes:slot.cancelMinutes,state:'booked',canCancel:Date.now()<Date.parse(slot.startsAt)-slot.cancelMinutes*60000}]}));resource.reload();return true;}} onCancel={async item=>{if(!await mutation.run('booking.cancel',{id:item.id}))return false;resource.update(data=>({...data,appointments:data.appointments.map(a=>a.id===item.id?{...a,state:'canceled',canCancel:false}:a)}));resource.reload();return true;}}/>;
}
export function CoachAppointments({workspaceId}:{workspaceId:string}){
 const resource=useResource<BookingData>(`workspaces/${workspaceId}/appointments`),mutation=useCommand();
 const [start,setStart]=useState(''),[end,setEnd]=useState(''),[cancelMinutes,setCancelMinutes]=useState(''),[error,setError]=useState(''),[cancel,setCancel]=useState<Appointment|null>(null);
 if(!resource.data)return <Pending error={resource.error} reload={resource.reload}/>;
 return <section className="gymaf-panel gymaf-stack"><h2>Call availability</h2><p>Publish exact start and end times and choose the cancellation notice. Times below use this device’s timezone. Booking a call does not create a coaching relationship or charge a client.</p><form className="gymaf-stack" onSubmit={async e=>{e.preventDefault();setError('');if(!start||!end||!cancelMinutes.trim()||!Number.isFinite(Date.parse(start))||!Number.isFinite(Date.parse(end))){setError('Complete the start, end and cancellation notice.');return;}if(await mutation.run('booking.slot-create',{workspaceId,startsAt:new Date(start).toISOString(),endsAt:new Date(end).toISOString(),cancelMinutes:Number(cancelMinutes)})){setStart('');setEnd('');resource.reload();}}}><Field label="Start" type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)} disabled={mutation.busy}/><Field label="End" type="datetime-local" required value={end} onChange={e=>setEnd(e.target.value)} disabled={mutation.busy}/><Field label="Cancellation notice (minutes, 0–10080)" type="number" min={0} max={10080} required value={cancelMinutes} onChange={e=>setCancelMinutes(e.target.value)} disabled={mutation.busy}/><button className="button primary" disabled={mutation.busy}>Publish Time Slot</button></form><ErrorNote message={error||mutation.error||resource.error}/><button className="button" disabled={mutation.busy} onClick={resource.reload}>Refresh Appointments</button>
 <h3>Published times</h3>{!resource.data.slots.length&&<p>No future times published.</p>}{resource.data.slots.filter(s=>s.state==='available').map(slot=><article key={slot.id}><p>{new Date(slot.startsAt).toLocaleString()} – {new Date(slot.endsAt).toLocaleTimeString()}</p><p>Cancellation notice: {slot.cancelMinutes} minutes · {slot.reserved?'Booked':'Available'}</p><button className="button" disabled={mutation.busy||slot.reserved} onClick={async()=>{if(await mutation.run('booking.withdraw',{id:slot.id}))resource.reload();}}>Withdraw Time</button></article>)}
 <h3>Appointments</h3>{resource.data.appointments.map(item=><article key={item.id}><p>{item.memberName||'Member'} · {new Date(item.startsAt).toLocaleString()} · {item.state}</p>{item.canCancel&&<button className="button" disabled={mutation.busy} onClick={()=>setCancel(item)}>Cancel Appointment</button>}</article>)}
 {cancel&&<Dialog title="Cancel member appointment?" onClose={()=>{if(!mutation.busy)setCancel(null);}}><p>{cancel.memberName} · {new Date(cancel.startsAt).toLocaleString()}</p><ErrorNote message={mutation.error}/><button className="button primary" disabled={mutation.busy} onClick={()=>setCancel(null)}>Keep Appointment</button><button className="button" disabled={mutation.busy} onClick={async()=>{if(await mutation.run('booking.cancel',{id:cancel.id})){setCancel(null);resource.reload();}}}>Cancel Appointment</button></Dialog>}
 </section>;
}
