"use client";
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { useEffect, useRef, useState, useSyncExternalStore } from 'react';
import { Check, ChevronLeft, CreditCard, QrCode, Send, X } from 'lucide-react';
import { api, invitationToken } from './api';
import { Dialog, ErrorNote, Field, Pending, useCommand, useResource } from './ui';
export type BillingData={relationshipId:string|null;workspaceId:string|null;coachName:string|null;offer:{title:string;sellerName:string;amountMinor:number;currency:string;enabled:boolean;livemode:boolean;revision:number}|null;subscription:{offer:{title:string;sellerName:string;amountMinor:number;currency:string;livemode:boolean};status:string;paidUntil:string|null;cancelAtPeriodEnd:boolean;blocked:boolean;syncedAt:string}|null;guestCredits:number;guestEligible:boolean;guestResetsAt:string;passes:{id:string;expiresAt:string;used:boolean;revoked:boolean}[]};
const money=(amount:number,currency:string)=>new Intl.NumberFormat('en-IE',{style:'currency',currency}).format(amount/100);
export function Membership({relationshipId,checkoutView=false}:{relationshipId?:string;checkoutView?:boolean}){
 const params=useSearchParams();
 const resource=useResource<BillingData>('me/billing'+(relationshipId?'?relationship='+relationshipId:'')),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const pending=useRef<{action:string;body:Record<string,unknown>}|null>(null),running=useRef(false);
 async function request(action:'checkout'|'portal'|'refresh'){
  if(running.current||!resource.data?.relationshipId)return;running.current=true;setBusy(true);setError('');
  if(pending.current?.action!==action)pending.current={action,body:{commandId:crypto.randomUUID(),relationshipId:resource.data.relationshipId,...(action==='checkout'?{offerRevision:resource.data.offer?.revision}:{})}};
  try{const result=await api<{url?:string;confirmed?:boolean;status?:string}>('billing/'+action,{method:'POST',body:pending.current.body});pending.current=null;
   if(result.url){const url=new URL(result.url);if(url.protocol!=='https:'||!['checkout.stripe.com','billing.stripe.com'].includes(url.hostname))throw new Error('Invalid payment destination.');window.location.assign(url.href);}
   else{setNotice(result.status==='pending'?'Payment is still pending. Finish checkout or check again shortly.':result.status==='expired'?'Checkout expired without confirmation. Refresh Membership before trying again.':'Payment status checked with Stripe.');resource.reload();}
  }catch(failure){setError(failure instanceof Error?failure.message:'Billing could not be confirmed. Retry.');}finally{running.current=false;setBusy(false);}
 }
 if(!resource.data)return <Pending error={resource.error} reload={resource.reload}/>;
 const {offer,subscription,coachName}=resource.data,hasSubscription=subscription&&!['canceled','incomplete_expired'].includes(subscription.status),displayOffer=hasSubscription?subscription.offer:offer;
 return <section className={`membership-page ${checkoutView?'membership-checkout':''}`}><header className="native-titlebar"><Link className="icon-button" href="/app/profile" aria-label="Back"><ChevronLeft/></Link><h1>{checkoutView?'Checkout':'Membership Plan'}</h1><span/></header>
 {checkoutView&&<div className="membership-coach"><h2>{coachName||'Your coaching'}</h2><p>Personal coaching with your connected coach</p></div>}
 {displayOffer?<><article className="membership-offer"><div><h2>Monthly</h2>{hasSubscription&&<Check aria-label="Current plan"/>}</div><p className="membership-price">{money(displayOffer.amountMinor,displayOffer.currency)}<span>/ month</span></p><p>{displayOffer.title}</p><p>Sold by {displayOffer.sellerName}</p>{!displayOffer.livemode&&<p className="billing-test-label">Test mode · no real payment</p>}{checkoutView&&<div className="membership-total"><span>Due today</span><strong>{money(displayOffer.amountMinor,displayOffer.currency)}</strong></div>}</article><p>Renews monthly at the displayed price. Cancel before renewal in Manage Billing; access continues through the paid period. No annual commitment.</p></>:<p>Your coach has not enabled paid membership yet. Your existing coaching access is unchanged.</p>}
 {subscription&&<div className="membership-status"><h2>{subscription.blocked?'Payment needs review':subscription.cancelAtPeriodEnd?'Renewal canceled':subscription.status.replaceAll('_',' ')}</h2>{subscription.paidUntil&&<p>Paid access through {new Date(subscription.paidUntil).toLocaleString()}</p>}<p>Card details, invoices and cancellation are available in Stripe.</p></div>}
 {params.get('checkout')==='returned'&&<p>Checkout returned. Check Payment Status to confirm access with Stripe.</p>}
 <div className="membership-actions"><ErrorNote message={error||resource.error}/>{notice&&<p role="status">{notice}</p>}{hasSubscription?<><button className="button primary full" disabled={busy} onClick={()=>void request('portal')}><CreditCard size={18}/>{busy?'Opening…':'Manage Billing'}</button></>:offer?.enabled&&resource.data.relationshipId?checkoutView?<button className="button primary full" disabled={busy} onClick={()=>void request('checkout')}><CreditCard size={18}/>{busy?'Opening secure checkout…':'Continue to Secure Checkout'}</button>:<Link className="button primary full" href="/app/checkout">Choose Monthly</Link>:null}{resource.data.relationshipId&&<button className="button full" disabled={busy} onClick={()=>void request('refresh')}>Check Payment Status</button>}<button className="button full" disabled={busy} onClick={()=>{pending.current=null;resource.reload();setNotice('Offer refreshed.');}}>Refresh Membership</button></div>
 {checkoutView&&<p className="billing-fine">Stripe collects your card securely and shows the final total before you confirm. Returning here does not prove payment; use Check Payment Status after checkout.</p>}<Link href="/app/settings/support">Billing help or refund request</Link>
 </section>;
}
export function GuestPasses(){
 const resource=useResource<BillingData>('me/billing'),mutation=useCommand(),[link,setLink]=useState(''),[linkId,setLinkId]=useState(''),[qr,setQr]=useState(''),[showQr,setShowQr]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const generated=useRef<{action:string;token:string}|null>(null);
 useEffect(()=>{if(!link)return;let alive=true;void import('qrcode').then(m=>m.toDataURL(link,{width:480,margin:3,errorCorrectionLevel:'M'})).then(value=>{if(alive)setQr(value);}).catch(()=>{if(alive)setError('QR could not load. Copy the link below.');});return()=>{alive=false;};},[link]);
 async function create(replaceId?:string){
  if(!resource.data?.relationshipId)return;const action=replaceId||'new';if(generated.current?.action!==action)generated.current={action,token:invitationToken()};
  const token=generated.current.token,result=await mutation.run(replaceId?'guest.replace-link':'guest.create',replaceId?{id:replaceId,token}:{relationshipId:resource.data.relationshipId,token});
  if(result){setLink(window.location.origin+'/guest-pass#pass='+token);setLinkId(result.id);generated.current=null;setNotice(replaceId?'New private link ready. The old link no longer works.':'Guest pass created.');resource.reload();}
 }
 async function share(){try{if(navigator.share)await navigator.share({title:'A week of coaching on Gymaf',url:link});else{await navigator.clipboard.writeText(link);setNotice('Link copied.');}}catch(failure){if(!(failure instanceof DOMException&&failure.name==='AbortError'))setError('Select and copy the private link below.');}}
 if(!resource.data)return <Pending error={resource.error} reload={resource.reload}/>;const data=resource.data;
 return <section className="guest-pass-page"><Link className="icon-button" href="/app/friends" aria-label="Close Guest Passes"><X/></Link><h1>Invite Friends to Gymaf</h1><p>Give a new client seven days with your coach. No card, no automatic renewal. Paid members receive three passes each calendar month.</p><div className="guest-pass-actions">{link?<><button className="icon-button" aria-label="Show guest pass QR" onClick={()=>setShowQr(true)}><QrCode/></button><button className="button primary" onClick={()=>void share()}><Send size={20}/>Share Guest Pass</button></>:<button className="button primary full" disabled={mutation.busy||data.guestCredits<1} onClick={()=>void create()}><Send size={20}/>{mutation.busy?'Creating…':'Create Guest Pass'}</button>}</div>{link&&data.guestCredits>0&&<button className="button full" disabled={mutation.busy} onClick={()=>void create()}>Create Another Guest Pass</button>}<ErrorNote message={error||mutation.error||resource.error}/>{notice&&<p role="status">{notice}</p>}
 {link&&<label className="form-field">Private guest-pass link<input readOnly value={link} onFocus={e=>e.target.select()}/></label>}<h2>Guest Pass Credits</h2><div className="guest-credit-stats"><p><span>Available</span><strong>{data.guestCredits}</strong></p><p><span>Created</span><strong>{data.passes.length}</strong></p><p><span>Accepted</span><strong>{data.passes.filter(p=>p.used).length}</strong></p></div><p className="billing-fine">Allowance resets {new Date(data.guestResetsAt).toLocaleString()}. Unused credits do not roll over. Created passes expire after 30 days; revoking one does not restore the credit. One trial per new client, while the sender’s paid membership is current and the coach has capacity.</p>{!data.guestEligible&&<p>An active paid subscription with guest passes enabled is required to create a pass.</p>}
 {!data.passes.length?<p className="guest-empty">No guest passes yet</p>:data.passes.map((pass,i)=><article className="guest-pass-row" key={pass.id}><div><h3>Guest Pass {i+1}</h3><p>{pass.used?'Accepted':pass.revoked?'Revoked':'Expires '+new Date(pass.expiresAt).toLocaleDateString()}</p></div>{!pass.used&&!pass.revoked&&<div className="guest-pass-row-actions"><button className="button" disabled={mutation.busy} onClick={()=>void create(pass.id)}>Replace Link</button><button className="button" disabled={mutation.busy} onClick={async()=>{if(await mutation.run('guest.revoke',{id:pass.id})){if(linkId===pass.id){setLink('');setLinkId('');}generated.current=null;resource.reload();}}}>Revoke</button></div>}</article>)}<p className="billing-fine">Lost a link? Replace Link keeps the same pass and credit usage; its previous link stops working.</p><Link className="button full" href="/app/account/plan">View Membership</Link>
 {showQr&&<Dialog title="Your guest pass" className="friends-qr" onClose={()=>setShowQr(false)}>{qr?<img src={qr} width={240} height={240} alt="Private guest pass QR code"/>:<p>Preparing QR…</p>}{/* eslint-disable-line @next/next/no-img-element -- Local generated QR. */}<p>For one new client. Share privately.</p><button className="button primary full" onClick={()=>void share()}>Share Guest Pass</button></Dialog>}</section>;
}
const subscribe=(fn:()=>void)=>{window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn);};
export function GuestPassJoin(){
 const router=useRouter();
 const token=useSyncExternalStore(subscribe,()=>new URLSearchParams(location.hash.slice(1)).get('pass')||'',()=>''),[preview,setPreview]=useState<{coachName:string;expiresAt:string;ownPass:boolean}|null>(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);const mutation=useCommand();
 useEffect(()=>{if(!token)return;const controller=new AbortController();void api<{coachName:string;expiresAt:string;ownPass:boolean}>('billing/guest-preview',{method:'POST',body:{token},signal:controller.signal}).then(value=>{if(!controller.signal.aborted){setPreview(value);setError('');}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[token,attempt]);
 return <div className="gymaf-connected gymaf-client"><main className="app-shell"><section className="guest-pass-page"><h1>Your week of coaching</h1><p>{preview?`Seven days with ${preview.coachName}.`:'Open your complete private guest-pass link.'}</p><p>For new Gymaf clients only. Accepting connects you to this coach for a seven-day trial. No card is required and the trial ends automatically. You choose whether to subscribe afterward.</p><ErrorNote message={error||mutation.error}/>{error&&<><Link className="button" target="_blank" rel="noopener noreferrer" href="/login">Sign In in a New Tab</Link><button className="button" onClick={()=>setAttempt(n=>n+1)}>Retry Guest Pass</button></>}{preview&&!preview.ownPass&&<button className="button primary full" disabled={mutation.busy} onClick={async()=>{if(await mutation.run('guest.accept',{token}))router.replace('/app');}}>{mutation.busy?'Starting…':'Start My Seven Days'}</button>}{preview?.ownPass&&<p>This is your pass. Share it with a new client.</p>}<Link href="/app">Back to Gymaf</Link></section></main></div>;
}
export function BillingSetup({workspaceId}:{workspaceId:string}){
 const [accountId,setAccountId]=useState(''),[amount,setAmount]=useState('99'),[capacity,setCapacity]=useState('10'),[revision,setRevision]=useState('0'),[enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const pending=useRef<{fingerprint:string;id:string}|null>(null);
 return <form className="gymaf-stack billing-setup" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');const payload={workspaceId,accountId,amountMinor:Math.round(Number(amount)*100),guestCapacity:Number(capacity),revision:Number(revision),enabled},fingerprint=JSON.stringify(payload);if(pending.current?.fingerprint!==fingerprint)pending.current={fingerprint,id:crypto.randomUUID()};try{await api('billing/configure',{method:'POST',body:{...payload,commandId:pending.current.id}});pending.current=null;setRevision(String(Number(revision)+1));setNotice('Offer saved using the verified Stripe seller and monthly price.');}catch(failure){setError(failure instanceof Error?failure.message:'Could not configure billing.');}finally{setBusy(false);}}}><h4>Stripe membership setup</h4><p>Default: €99 monthly, no application fee, three seven-day guest passes per paid member per month. Set the coach’s verified Stripe account; the seller name comes from Stripe.</p><Field label="Stripe seller account" value={accountId} required pattern="acct_[A-Za-z0-9]+" onChange={e=>setAccountId(e.target.value)}/><Field label="Monthly EUR price, tax-inclusive" type="number" min={1} max={10000} step="0.01" value={amount} required onChange={e=>setAmount(e.target.value)}/><Field label="Maximum simultaneous guest trials" type="number" min={0} max={100} value={capacity} required onChange={e=>setCapacity(e.target.value)}/><Field label="Current offer revision (0 for new)" type="number" min={0} value={revision} required onChange={e=>setRevision(e.target.value)}/><label><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Enable membership and guest-pass acceptance</label><button className="button" disabled={busy}>{busy?'Saving…':'Save Verified Stripe Offer'}</button><ErrorNote message={error}/>{notice&&<p role="status">{notice}</p>}</form>;
}
