"use client";
import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { progressData } from "./progress-data";
import { useState, type ReactNode } from "react";
import { CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight, Dumbbell, List, MessageCircle, Pencil, Settings, X } from "lucide-react";
import type { Bootstrap, RelationshipDetail, ScheduledWorkout } from "@/shared/gymaf/contracts";
import { localDate } from "@/shared/gymaf/validation";
import { Dialog, Empty, ErrorNote, Field, Head, Row } from "./ui";

export type Artwork = { src: string; alt: string };
export function TrainingArtwork({ artwork, className = "" }: { artwork?: Artwork; className?: string }) {
  return <div className={`training-artwork ${className}`}>{artwork ? <Image src={artwork.src} alt={artwork.alt} fill sizes="(max-width: 759px) 100vw, 540px"/> : <div className="training-artwork-empty"><Dumbbell size={44}/><span>GYMAF</span></div>}</div>;
}
export function InitialAvatar({ name, size = 36 }: { name: string; size?: number }) { return <span className="gymaf-initial-avatar" style={{width:size,height:size}} aria-hidden="true">{name.trim().split(/\s+/).slice(0,2).map(s=>s[0]).join("")||"G"}</span>; }
export function WorkoutTile({ workout, query = "", artwork }: { workout: ScheduledWorkout; query?: string; artwork?: Artwork }) {
  const minutes = workout.prescription.exercises.reduce((total,exercise)=>total+exercise.sets.reduce((n,set)=>n+(set.durationSeconds||0)+set.restSeconds,0),0);
  return <article className="today-card connected-workout-card"><Link className="today-photo" href={`/app/workouts/${workout.id}${query}`} aria-label={`Open ${workout.prescription.title}`}><TrainingArtwork artwork={artwork}/></Link><Link className="today-copy" href={`/app/workouts/${workout.id}${query}`}><h3>{workout.prescription.title}</h3><p>{workout.prescription.exercises.length} exercises{minutes>0?` · ${Math.ceil(minutes/60)} min timed work and rest`:""}</p></Link></article>;
}
export function ClientHome({ account, data, query, artwork }: { account: Bootstrap; data: RelationshipDetail; query: string; artwork?: Artwork }) {
  const router=useRouter();
  const today=localDate(account.user.timezone);
  const upcoming=[...data.workouts].filter(w=>w.state==='assigned').sort((a,b)=>a.scheduled_date.localeCompare(b.scheduled_date));
  const next=upcoming.find(w=>w.scheduled_date>=today)||upcoming[0];
  const completed=data.sessions.filter(s=>s.state==='completed');
  return <div className="connected-home"><Head title={`${account.user.locale==='bg'?'Здравей':'Hello'}, ${account.user.display_name.split(' ')[0]||'there'}`}/>
    {account.relationships.length>1&&<label className="form-field relationship-switch">Coach<select value={data.relationship.id} onChange={e=>router.push('/app?relationship='+e.target.value)}>{account.relationships.map(r=><option key={r.id} value={r.id}>{r.coach_name||'Coach'}</option>)}</select></label>}
    <div className="home-grid"><div className="today-column"><h2>{account.user.locale==='bg'?'Днес':'Today'}</h2>{next?<WorkoutTile workout={next} query={query} artwork={artwork}/>:<Empty>Your next workout will appear here when your coach assigns it.</Empty>}
      <Link className="button full connected-more-workouts" href={`/app/workouts${query}`}>More Workouts</Link><section className="connected-quick-links"><h2>Your training</h2><div><Link href={`/app/schedule${query}`}><CalendarDays/><span>Schedule</span></Link><Link href={`/app/history${query}`}><List/><span>History</span></Link><Link href={`/app/check-ins${query}`}><Check/><span>Check-in</span></Link><Link href={`/app/messages${query}`}><MessageCircle/><span>Coach</span></Link></div></section></div>
      <div className="week-column"><section className="connected-training-summary"><div><h2>Your progress</h2><span className="progress-emblem"><Check/></span></div><p>{completed.length} completed {completed.length===1?'workout':'workouts'} in your loaded history</p><Link href={`/app/history${query}`}>View progress <ChevronRight size={18}/></Link></section><section className="this-week"><h2>Coming up</h2>{upcoming.slice(0,5).map(w=><div className="connected-upcoming" key={w.id}><p>{new Date(w.scheduled_date+'T12:00:00').toLocaleDateString(account.user.locale,{weekday:'long',month:'short',day:'numeric'})}</p><Row href={`/app/workouts/${w.id}${query}`} detail={`${w.prescription.exercises.length} exercises`}>{w.prescription.title}</Row></div>)}<div className="button-row"><Link className="button" href={`/app/schedule${query}`}>Edit Schedule</Link><Link className="button" href={`/app/history${query}`}>View History</Link></div></section></div></div>
  </div>;
}
export function WorkoutDetailView({ workout, children, query, artwork }: { workout: ScheduledWorkout; children: ReactNode; query: string; artwork?: Artwork }) {
  const [overview,setOverview]=useState(false);
  const totalSets=workout.prescription.exercises.reduce((n,e)=>n+e.sets.length,0);
  const timedSeconds=workout.prescription.exercises.reduce((n,e)=>n+e.sets.reduce((sum,s)=>sum+(s.durationSeconds||0)+s.restSeconds,0),0);
  return <section className="connected-workout-detail"><TrainingArtwork artwork={artwork}/><header><Link className="icon-button" href={`/app${query}`} aria-label="Back"><ChevronDown/></Link></header><div className="connected-detail-title"><h1>{workout.prescription.title}</h1><p>{workout.prescription.exercises.length} exercises</p></div><footer><button className="connected-detail-meta" onClick={()=>setOverview(true)}><span>{totalSets} {totalSets===1?'set':'sets'}<small>{timedSeconds>0?`${Math.ceil(timedSeconds/60)} min timed work and rest`:'View exercise instructions'}</small></span><ChevronRight/></button><div className="connected-detail-actions"><button className="icon-button" onClick={()=>setOverview(true)} aria-label="Workout overview"><List/></button><div className="connected-detail-start">{children}</div></div></footer>{overview&&<Dialog title="Workout Overview" onClose={()=>setOverview(false)}><div className="connected-overview">{workout.prescription.exercises.map(exercise=><article key={exercise.id}><span className="exercise-glyph"><Dumbbell/></span><div><h3>{exercise.name}</h3><small>{exercise.sets.length} sets</small><p>{exercise.instructions}</p>{exercise.sets.map((s,i)=><p className="prescribed-set" key={i}>Set {i+1}: {[s.reps!==null?`${s.reps} reps`:'',s.loadKg!==null?`${s.loadKg} kg`:'',s.durationSeconds?`${s.durationSeconds}s`:'',s.distanceM?`${s.distanceM}m`:'',`${s.restSeconds}s rest`].filter(Boolean).join(' · ')}</p>)}</div></article>)}</div></Dialog>}</section>;
}
export function ScheduleView({ data, query, onMove, busy = false, error }: { data: RelationshipDetail; query: string; onMove: (w: ScheduledWorkout,date:string)=>Promise<boolean>; busy?:boolean; error?:string }) {
  const [editing,setEditing]=useState<ScheduledWorkout|null>(null),[date,setDate]=useState(''),[week,setWeek]=useState(0);
  const today=localDate(data.client.timezone),start=new Date(today+'T12:00:00');start.setDate(start.getDate()-((start.getDay()+6)%7)+week*7);
  const days=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return d;});
  return <section className="connected-schedule"><header className="native-titlebar"><Link className="icon-button" href={`/app${query}`} aria-label="Close schedule"><X/></Link><h1>Edit Schedule</h1><Link href={`/app${query}`} className="icon-button" aria-label="Done"><Check/></Link></header><div className="schedule-week"><button className="icon-button" aria-label="Previous week" onClick={()=>setWeek(week-1)}><ChevronLeft/></button><span>{start.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</span><button className="icon-button" aria-label="Next week" onClick={()=>setWeek(week+1)}><ChevronRight/></button></div><div className="connected-schedule-days">{days.map(d=>{const dateKey=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;const entries=data.workouts.filter(w=>w.scheduled_date===dateKey&&w.state!=='canceled');return <div className="schedule-day" key={dateKey}><div className={`schedule-date ${dateKey===today?'today':''}`}><small>{d.toLocaleDateString('en-US',{weekday:'short'}).slice(0,1)}</small><b>{d.getDate()}</b></div><div>{entries.length?entries.map(w=><article className="schedule-workout" key={w.id}><Link href={`/app/workouts/${w.id}${query}`}><span className="exercise-glyph">{w.state==='completed'?<Check/>:<Dumbbell/>}</span><span>{w.prescription.title}<small>{w.prescription.exercises.length} exercises</small></span></Link>{w.state==='assigned'&&data.can_train&&<button aria-label={`Move ${w.prescription.title}`} onClick={()=>{setEditing(w);setDate(w.scheduled_date);}}><CalendarDays size={20}/></button>}</article>):<p className="schedule-rest">Rest Day</p>}</div></div>;})}</div><p className="schedule-help">Your coach assigns workouts. Select the calendar beside a workout to change its date.</p>{editing&&<Dialog title="Move Workout" onClose={()=>{if(!busy)setEditing(null);}}><h3>{editing.prescription.title}</h3><form className="gymaf-stack" onSubmit={async e=>{e.preventDefault();if(await onMove(editing,date))setEditing(null);}}><Field label="Workout date" type="date" required value={date} onChange={e=>setDate(e.target.value)}/><ErrorNote message={error}/><button className="button primary full" disabled={busy}>{busy?'Saving…':'Save'}</button></form></Dialog>}</section>;
}
export function ProgressView({ data, query, user, onGoal, busy=false, error }: { data: RelationshipDetail; query:string; user:Bootstrap['user'];onGoal:(goal:string)=>Promise<boolean>;busy?:boolean;error?:string }) {
  const [tab,setTab]=useState('Goals'),[goalOpen,setGoalOpen]=useState(false),[goal,setGoal]=useState(user.goal),[day,setDay]=useState('');
  const today=localDate(user.timezone);
  const {done,recent,start,dates,week,active,dateOf:sessionDate}=progressData(data.sessions,user.timezone,today);
  const minutes=Math.round(week.reduce((n,day)=>n+day.minutes,0));
  return <section className="connected-progress"><Head title="Progress"/><div className="tabs" role="group" aria-label="Progress view">{['Goals','Metrics'].map(t=><button key={t} className={tab===t?'active':''} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==='Goals'?<><h2>My Goal</h2><article className="connected-goal"><h3>{user.goal||'Set your training goal'}</h3>{user.goal==='Increase Muscle Mass'&&<p>Build muscle that moves mountains.</p>}</article><button className="connected-change-goal" onClick={()=>{setGoal(user.goal);setGoalOpen(true);}}>Change Goal</button><h2>Workout Consistency</h2><article className="consistency-card"><header><CalendarDays size={19}/><span>Past 30 Days</span></header><div className="calendar-grid">{['M','T','W','T','F','S','S'].map((d,i)=><small key={i}>{d}</small>)}{dates.map(k=><button key={k} className={`${active.has(k)?'active-day ':''}${k<start||k>today?'outside':''}`} aria-label={`View ${k} workouts`} disabled={k>today} onClick={()=>setDay(k)}>{Number(k.slice(-2))}</button>)}</div><div className="calendar-stats"><span><small>Active Days</small><b>{active.size} days</b></span><span><small>Completed Workouts</small><b>{recent.length}</b></span></div></article></>:<><h2>My Metrics</h2><Row href={`/app/progress/weight${query}`}>Weight</Row><Row href={`/app/progress/photos${query}`}>Progress Photos</Row><article className="connected-minutes"><h3>Active Minutes</h3><div className="minute-columns">{week.map(({day,minutes:n})=><div key={day}><i aria-label={`${day}: ${Math.round(n)} minutes`} style={{height:(n/Math.max(1,...week.map(d=>d.minutes))*100)+'%'}}/><small>{new Date(day+'T12:00:00Z').toLocaleDateString('en-US',{weekday:'short',timeZone:'UTC'})}</small></div>)}</div><p>{minutes} min <small>in the past 7 days</small></p></article></>}
    <h2>Workout History</h2><div className="gymaf-row-list">{data.sessions.length?data.sessions.map(s=><Row key={s.id} href={`/app/sessions/${s.id}${query}`} detail={`${new Date(s.started_at).toLocaleDateString()} · ${s.state.replaceAll('_',' ')}`}>{s.prescription.title}</Row>):<Empty>Your completed workouts will appear here.</Empty>}</div><p className="loaded-scope">Showing {data.sessions.length} loaded attempts.</p>
    {goalOpen&&<Dialog title="Change Goal" onClose={()=>{if(!busy)setGoalOpen(false);}}><p>Choose what you want to work towards.</p><form className="gymaf-stack" onSubmit={async e=>{e.preventDefault();if(await onGoal(goal))setGoalOpen(false);}}><div className="goal-options">{['Lose Weight','Get Toned','Increase Muscle Mass','Improve Health and Longevity','Improve Sports Performance'].map(g=><button type="button" key={g} aria-pressed={goal===g} onClick={()=>setGoal(g)}>{g}{goal===g&&<Check size={20}/>}</button>)}</div><Field label="Your goal" value={goal} maxLength={500} onChange={e=>setGoal(e.target.value)} required/><ErrorNote message={error}/><button className="button primary full" disabled={busy}>{busy?'Saving…':'Save Goal'}</button></form></Dialog>}
    {day&&<Dialog title={new Date(day+'T12:00:00').toLocaleDateString('en-US',{month:'long',day:'numeric'})} onClose={()=>setDay('')}>{done.filter(s=>sessionDate(s)===day).length?done.filter(s=>sessionDate(s)===day).map(s=><Row key={s.id} href={`/app/sessions/${s.id}${query}`}>{s.prescription.title}</Row>):<p>No completed workouts recorded on this day.</p>}<Link href={`/app/schedule${query}`} className="button full">View Schedule</Link></Dialog>}
  </section>;
}
export function ProfileOverview({ account, data, query, avatar, cover }: { account:Bootstrap; data?:RelationshipDetail; query:string; avatar?:ReactNode; cover?:ReactNode }) {
  const done=data?.sessions.filter(s=>s.state==='completed')||[];
  return <section className="connected-profile"><div className="connected-profile-cover">{cover}</div><div className="profile-actions"><Link className="icon-button" href={`/app/profile/edit${query}`} aria-label="Edit profile"><Pencil/></Link><Link className="icon-button" href={`/app/settings${query}`} aria-label="Settings"><Settings/></Link></div><div className="connected-profile-info"><div className="profile-own-avatar">{avatar||<InitialAvatar name={account.user.display_name} size={86}/>}</div><h1>{account.user.display_name||'Your Profile'}</h1><p>{account.user.goal||'Your training journey starts here.'}</p><div className="profile-totals"><div><b>{done.length}</b><small>Workouts</small></div><div><b>{Math.round(done.reduce((n,s)=>n+s.elapsed_seconds,0)/60)}</b><small>Active Minutes</small></div></div><p className="loaded-scope">From loaded completed workouts</p><Link className="button" href={`/app/profile/edit${query}`}>Edit Profile</Link></div><div className="connected-profile-rows"><h2>Your Coach</h2>{data?<Link className="profile-coach-row" href={`/app/messages${query}`}><InitialAvatar name={data.relationship.coach_name}/><span>{data.relationship.coach_name||'Your coach'}<small>{data.relationship.state}</small></span><ChevronRight/></Link>:<Empty>Connect with your coach using their invitation.</Empty>}<Row href={`/app/coaches${data?'/change':''}${query}`}>{data?'Change Coach':'Explore Coaches'}</Row><h2>Travel &amp; Events</h2><Row href={`/app/profile/event${query}`}>Add Travel or Event</Row><h2>Training</h2><Row href={`/app/history${query}`}>Workout History</Row><Row href={`/app/check-ins${query}`}>Weekly Check-ins</Row><h2>About You</h2><p>{account.user.equipment||'Add your equipment to help your coach plan.'}</p><p>{account.user.availability}</p></div></section>;
}
