"use client";
import Link from 'next/link';
import { useState } from 'react';
import { ArrowRight, Check, ChevronLeft, ChevronRight, Search, X } from 'lucide-react';
import type { Bootstrap, CoachDirectory as Directory, DirectoryCoach } from '@/shared/gymaf/contracts';
import { coachExpertise,coachStyles,coachSports,coachLanguages } from '@/shared/gymaf/validation';
import { Dialog, ErrorNote, Pending } from './ui';
import { InitialAvatar } from './client-views';
import { emptyDirectoryFilters,filterDirectory,getDirectoryFilters,putDirectoryFilters,type DirectoryFilters } from './directory-data';
import { useResource } from './ui';

const groups=[['expertise','Expertise',coachExpertise],['styles','Coaching Style',coachStyles],['sports','Sports',coachSports],['languages','Languages',coachLanguages]] as const;
export const changeReasons=['Ready for something new','Different coach personality','Goal-specific expertise','Mismatch in training style','Different workouts','Faster results','Something else'];
export function CoachDirectory({account,path,query}:{account:Bootstrap;path:string[];query:string}){
  const resource=useResource<Directory>('public/directory');
  if(!resource.data)return <Pending error={resource.error} reload={resource.reload}/>;
  return <DirectoryView key={account.user.id} ownerId={account.user.id} data={resource.data} path={path} query={query} error={resource.error} retry={resource.reload}/>;
}
function DirectoryView({ownerId,data,path,query,error,retry}:{ownerId:string;data:Directory;path:string[];query:string;error?:string;retry:()=>void}){
  const [filters,setFilters]=useState(()=>getDirectoryFilters(ownerId)),[index,setIndex]=useState(0),[invitation,setInvitation]=useState<DirectoryCoach|null>(null);
  const filtered=filterDirectory(data.coaches,filters),mode=path[1]||'',coach=mode==='profile'?data.coaches.find(item=>item.slug===path[2]):undefined,selected=filtered[Math.min(index,Math.max(0,filtered.length-1))];
  const href=(suffix='')=>`/app/coaches${suffix}${query}`;
  function update(value:DirectoryFilters){putDirectoryFilters(ownerId,value);setFilters(value);setIndex(0);}
  function toggle(key:'expertise'|'styles'|'sports'|'languages'|'reasons',value:string){update({...filters,[key]:filters[key].includes(value)?filters[key].filter(item=>item!==value):[...filters[key],value]});}
  const back=mode==='search'||mode==='results'?href():mode==='reasons'?href('/change'):`/app/profile${query}`;
  const status=<>{error&&<div className="directory-warning"><ErrorNote message={error}/><button onClick={retry}>Retry directory</button></div>}{data.hasMore&&<p className="directory-note">Showing the first 500 listed coaches. Search counts apply to these profiles.</p>}</>;
  const empty=<div className="directory-empty"><h2>{data.coaches.length?'No coaches match these filters':'No coaches listed yet'}</h2><p>{data.coaches.length?'Try fewer filters or a different name.':'Invited coaches appear here after they choose to publish and list their profile.'}</p>{data.coaches.length>0&&<button className="button" onClick={()=>update(emptyDirectoryFilters())}>Clear Filters</button>}<button className="button" onClick={retry}>Refresh</button></div>;
  if((mode==='profile'&&!coach)||!['','profile','change','reasons','search','results'].includes(mode))return <section className="directory-empty"><h1>Coach profile unavailable</h1><p>This profile may have been unlisted or unpublished.</p><Link className="button" href={href('/results')}>Browse Coaches</Link></section>;
  if(mode==='change'||mode==='reasons')return <section className="directory-change"><header className="native-titlebar"><Link className="icon-button" href={back} aria-label={mode==='change'?'Close Change Coach':'Back'}>{mode==='change'?<X/>:<ChevronLeft/>}</Link><h1>Change Coach</h1><span/></header>{mode==='change'?<>{selected?<div className="directory-change-portrait"><InitialAvatar name={selected.name} size={120}/><div><h2>{selected.name}</h2><p>{selected.details.expertise.slice(0,2).join(' · ')}</p></div></div>:<div className="directory-change-empty">{empty}</div>}<h2>Find your next coach</h2><p>Browse by specialty and training style. Exploring does not change your current coaching relationship.</p><div className="directory-change-actions"><Link className="button primary" href={href('/reasons')}>Explore</Link><Link className="button" href={`/app/settings/support${query}`}>Contact Us</Link></div></>:<><h2>Is there anything in particular you’re looking for from a new coach?</h2><p>Keep track of what you’d like to change while you explore. These choices are not sent to your coach.</p><div className="directory-reasons">{changeReasons.map(value=><button type="button" aria-pressed={filters.reasons.includes(value)} key={value} onClick={()=>toggle('reasons',value)}><span>{filters.reasons.includes(value)&&<Check size={15}/>}</span>{value}</button>)}</div><Link className="button primary full directory-reasons-next" href={href('/search')}>Continue</Link></>}{status}</section>;
  if(mode==='search')return <section className="directory-search"><header><button disabled={!groups.some(([key])=>filters[key].length)&&!filters.search} onClick={()=>update(emptyDirectoryFilters())}>Clear All</button><h1>Find Your Coach</h1><Link className="icon-button" href={href('/results')} aria-label="Close coach filters"><X size={20}/></Link></header><div className="directory-filter-body">{groups.map(([key,label,choices])=><section key={key}><div className="directory-filter-label"><h2>{label}</h2>{key==='expertise'&&filters.expanded&&<label>Sort <select aria-label="Sort expertise" value={filters.sort} onChange={event=>update({...filters,sort:event.target.value as DirectoryFilters['sort']})}><option>Default order</option><option>A–Z</option></select></label>}</div><div className="directory-chips">{(key==='expertise'&&!filters.expanded?['Sports Performance','General Strength Training','Weight Loss','Nutrition','Bodybuilding']:filters.sort==='A–Z'?[...choices].sort():choices).map(value=><button type="button" key={value} aria-pressed={filters[key].includes(value)} onClick={()=>toggle(key,value)}><span>{value}</span></button>)}</div>{key==='expertise'&&<button className="directory-see-more" aria-expanded={filters.expanded} onClick={()=>update({...filters,expanded:!filters.expanded})}>{filters.expanded?'See Less':'See More'}</button>}</section>)}{status}</div><footer><Link href={href('/results')}>Show Coaches ({filtered.length})</Link></footer></section>;
  return <section className="directory-dark"><header className="directory-head"><Link className="icon-button" aria-label="Back" href={coach?href('/results'):back}><ChevronLeft/></Link><h1>{coach?coach.name:mode==='results'?'Find Your Coach':'Explore Coaches'}</h1><Link href={href('/search')}>{mode==='results'?'Edit':<Search aria-label="Find your coach" size={20}/>}</Link></header>{status}
    {coach?<><div className="directory-profile-hero"><InitialAvatar name={coach.name} size={128}/><span className="directory-photo-note">Coach photo not provided</span></div><article className="directory-profile-copy"><h2>{coach.name}</h2>{groups.filter(([key])=>key==='expertise'&&coach.details[key].length>0).map(([key,label])=><section key={key}><h3>{key==='expertise'?'Specialties':label}</h3>{coach.details[key].map(value=><p key={value}>{value}</p>)}</section>)}<section><h3>About</h3><p>{coach.bio||'This coach has not added a biography yet.'}</p></section>{([['experience','Experience'],['qualifications','Qualifications'],['loves','Loves'],['location','Located']] as const).filter(([key])=>coach.details[key]).map(([key,label])=><section key={key}><h3>{label}</h3><p>{coach.details[key]}</p></section>)}{groups.filter(([key])=>key!=='expertise'&&coach.details[key].length>0).map(([key,label])=><section key={key}><h3>{label}</h3>{coach.details[key].map(value=><p key={value}>{value}</p>)}</section>)}<p className="directory-note">Profile details are provided by this coach.</p></article><div className="directory-bottom-action"><button onClick={()=>setInvitation(coach)}>Connect with {coach.name}</button></div></>:mode==='results'?<><label className="directory-text-search"><Search size={18}/><input aria-label="Search coaches" placeholder="Search coaches" value={filters.search} onChange={event=>update({...filters,search:event.target.value})}/></label><div className="directory-active-filters">{groups.flatMap(([key])=>filters[key].map(value=><button key={`${key}:${value}`} onClick={()=>toggle(key,value)} aria-label={`Remove ${value} filter`}>{value}<X size={14}/></button>))}</div>{!filtered.length?empty:<ul className="directory-results">{filtered.map(item=><li key={item.workspaceId}><Link href={href('/profile/'+item.slug)}><InitialAvatar name={item.name} size={64}/><div><h2>{item.name}</h2><p>{item.details.experience||item.bio||item.details.expertise.join(' · ')}</p></div><ChevronRight size={20}/></Link></li>)}</ul>}</>:<>{selected?<><div className="directory-featured-hero"><InitialAvatar name={selected.name} size={180}/><span className="directory-photo-note">Coach photo not provided</span></div><article className="directory-featured-copy"><h2>{selected.name}</h2><p>{selected.details.experience||selected.bio}</p><Link href={href('/profile/'+selected.slug)}>Learn More</Link></article><nav className="directory-pages" aria-label="Browse listed coaches"><button aria-label="Previous coach" disabled={index===0} onClick={()=>setIndex(index-1)}><ChevronLeft/></button><span>{Math.min(index,filtered.length-1)+1} of {filtered.length}</span><button aria-label="Next coach" disabled={index>=filtered.length-1} onClick={()=>setIndex(index+1)}><ChevronRight/></button></nav><div className="directory-explore-actions"><button onClick={()=>setInvitation(selected)}>Connect with {selected.name}</button><Link href={href('/results')}>View More Coaches</Link></div></>:empty}</>}
    {invitation&&<Dialog title={`Connect with ${invitation.name}`} onClose={()=>setInvitation(null)}><p>Coaching starts with a private invitation from this coach. Open their invitation link when you have it.</p><p>Browsing does not book a call, purchase training, or replace your current coach.</p><Link className="button primary full" href={`/app/settings/support${query}`}>Get Help Connecting <ArrowRight size={18}/></Link><button className="button full" onClick={()=>setInvitation(null)}>Keep Browsing</button></Dialog>}
  </section>;
}
