"use client";
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { Camera, ChevronLeft, Images, Trash2, Video } from 'lucide-react';
import { CameraCapture } from './camera-capture';
import { VideoRecorder } from './video-recorder';
import { api } from './api';
import { Dialog, ErrorNote, Pending, useCommand, useResource } from './ui';
import { getAttachmentDraft,putAttachmentDraft,forgetAttachmentDraft,type AttachmentDraft } from './attachment-drafts';

export type Attachment={id:string;relationship_id:string;session_id:string|null;exercise_id:string|null;exercise_name:string|null;mime_type:string;message_id:string|null;shared_at:string|null;created_at:string;owned:boolean};
export function AttachmentPreview({item}:{item:Attachment}){
 const [state,setState]=useState<{url?:string;error?:string}>({}),[attempt,setAttempt]=useState(0);
 useEffect(()=>{const controller=new AbortController();let url:string|undefined;void api<Blob>(`attachments/${item.id}/file`,{signal:controller.signal,responseType:'blob'}).then(blob=>{if(!controller.signal.aborted){url=URL.createObjectURL(blob);setState({url});}}).catch(()=>{if(!controller.signal.aborted)setState({error:'Media unavailable.'});});return()=>{controller.abort();if(url)URL.revokeObjectURL(url);};},[item.id,attempt]);
 return state.url?item.mime_type.startsWith('video/')?<video src={state.url} controls playsInline preload="metadata" aria-label={item.exercise_name||'Shared video'} onError={()=>setState({error:'This browser could not play the video.'})}/>:<img src={state.url} alt="Conversation attachment"/>:<div className="attachment-placeholder">{state.error?<><p>{state.error}</p><button className="button" onClick={()=>{setState({});setAttempt(n=>n+1);}}>Retry Media</button></>:<p role="status">Loading media…</p>}</div>; // eslint-disable-line @next/next/no-img-element -- Private authenticated object URL.
}
function FilePreview({file}:{file:File}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const url=URL.createObjectURL(file),element=document.createElement(file.type.startsWith('video/')?'video':'img');element.src=url;if(element instanceof HTMLVideoElement){element.controls=true;element.playsInline=true;}else element.alt='Selected attachment preview';ref.current?.replaceChildren(element);return()=>{element.remove();URL.revokeObjectURL(url);};},[file]);return <div ref={ref} className="attachment-file-preview"/>;}
export function AttachmentComposer({ownerId,relationshipId,coachName,sessionId,exerciseId,exerciseName,recordVideo=false,onClose,onShared}:{ownerId:string;relationshipId:string;coachName:string;sessionId?:string;exerciseId?:string;exerciseName?:string;recordVideo?:boolean;onClose:()=>void;onShared:()=>void}){
 const draftKey=`${ownerId}:${relationshipId}:${sessionId||''}:${exerciseId||''}`;
 const [draft,setDraft]=useState<AttachmentDraft|undefined>(()=>getAttachmentDraft(draftKey)),[camera,setCamera]=useState(false),[recording,setRecording]=useState(recordVideo&&!getAttachmentDraft(draftKey)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[discard,setDiscard]=useState(false);
 const mutation=useCommand(),running=useRef(false),controller=useRef<AbortController|null>(null),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;controller.current?.abort();};},[]);
 useEffect(()=>{if(!draft)return;const warn=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[draft]);
 function choose(file:File){if(!['image/jpeg','image/png','image/webp','video/mp4','video/webm'].includes(file.type)||!file.size||file.size>4194304){setError('Choose a photo or MP4/WebM video smaller than 4 MB.');return;}const value={id:crypto.randomUUID(),file,uploaded:false};putAttachmentDraft(draftKey,value);setDraft(value);setError('');setCamera(false);setRecording(false);}
 async function send(){if(!draft||running.current)return;running.current=true;setBusy(true);setError('');controller.current=new AbortController();try{if(!draft.uploaded){const params=new URLSearchParams({relationship:relationshipId});if(sessionId)params.set('session',sessionId);if(exerciseId)params.set('exercise',exerciseId);await api('me/attachments?'+params,{method:'POST',file:draft.file,uploadId:draft.id,signal:controller.current.signal});if(!mounted.current)return;const saved={...draft,uploaded:true};putAttachmentDraft(draftKey,saved);setDraft(saved);}if(await mutation.run('attachment.share',{id:draft.id})){forgetAttachmentDraft(draftKey);onShared();onClose();}}catch(failure){if(mounted.current)setError(failure instanceof Error?failure.message:'The upload could not be confirmed. Retry Send.');}finally{running.current=false;if(mounted.current)setBusy(false);}}
 function close(){if(running.current)return;if(draft)setDiscard(true);else onClose();}
 return <><Dialog title={exerciseName||'Share Photo or Video'} className="attachment-composer" onClose={close}>{draft?<><FilePreview file={draft.file}/><p>{draft.uploaded?'Uploaded privately. Send to share it with your conversation.':'This selection has not been shared.'}</p></>:<p>Choose a photo or record a short video for your conversation with {coachName}.</p>}<ErrorNote message={error||mutation.error}/>{!draft?.uploaded&&<div className="attachment-source-actions"><button className="button" disabled={busy} onClick={()=>setCamera(true)}><Camera size={18}/>Take Photo</button><button className="button" disabled={busy} onClick={()=>setRecording(true)}><Video size={18}/>Record Video</button><label className="button"><Images size={18}/>Photo / Video Library<input type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)choose(file);}}/></label></div>}{draft&&<button className="button primary full" disabled={busy} onClick={()=>void send()}>{busy?'Sending…':`Send to ${coachName}`}</button>}<p className="attachment-private-note">The other participant can view the file after you send. Removing it later revokes app access, but cannot erase a copy they already saved.</p></Dialog>{camera&&<CameraCapture onClose={()=>setCamera(false)} onPhoto={choose}/ >}{recording&&<VideoRecorder exerciseName={exerciseName} onClose={()=>setRecording(false)} onVideo={choose}/ >}{discard&&<Dialog title="Keep this attachment draft?" onClose={()=>setDiscard(false)}><p>{draft?.uploaded?'The uploaded file stays private in Shared Media until you send or remove it.':'Your selected file stays available while this page remains open.'}</p><button className="button primary" onClick={()=>setDiscard(false)}>Keep Editing</button><button className="button" onClick={()=>{setDiscard(false);onClose();}}>Leave and Keep Draft</button><button className="button" onClick={()=>{forgetAttachmentDraft(draftKey);onClose();}}>Discard Selection</button></Dialog>}</>;
}
export function SharedMedia({relationshipId,query,videosOnly=false,canSend}:{relationshipId:string;query:string;videosOnly?:boolean;canSend:boolean}){
 const resource=useResource<Attachment[]>(`relationships/${relationshipId}/attachments`),mutation=useCommand(),[viewing,setViewing]=useState<Attachment|null>(null),[deleting,setDeleting]=useState(false),[confirmRemove,setConfirmRemove]=useState(false),[error,setError]=useState('');
 async function remove(){if(!viewing||deleting)return;setDeleting(true);setError('');try{await api(`attachments/${viewing.id}`,{method:'DELETE'});setViewing(null);setConfirmRemove(false);resource.reload();}catch(failure){setError(failure instanceof Error?failure.message:'Could not remove the file. Retry.');}finally{setDeleting(false);}}
 if(!resource.data)return <Pending error={resource.error} reload={resource.reload}/>;
 const items=resource.data.filter(item=>!videosOnly||item.mime_type.startsWith('video/'));
 return <section className="shared-media"><header className="native-titlebar"><Link className="icon-button" href={`/app/messages${query}`} aria-label="Back"><ChevronLeft/></Link><h1>{videosOnly?'Videos':'Shared'}</h1><span/></header><Link className="button" href={`/app/messages/${videosOnly?'shared':'videos'}${query}`}>{videosOnly?'All Media':'Videos Only'}</Link><ErrorNote message={resource.error}/>{!items.length?<p>No {videosOnly?'videos':'photos or videos'} yet. Add one from your conversation.</p>:<div className="attachment-grid">{items.map(item=><article key={item.id}><button onClick={()=>{setViewing(item);setError('');setConfirmRemove(false);}} aria-label={`Open ${item.mime_type.startsWith('video/')?'video':'photo'} ${item.exercise_name||new Date(item.created_at).toLocaleDateString()}`}><span>{item.mime_type.startsWith('video/')?<Video/>:<Images/>}</span><strong>{item.exercise_name||new Date(item.created_at).toLocaleDateString()}</strong><small>{item.shared_at?'Shared':'Private draft'}</small></button></article>)}</div>}<button className="button" onClick={resource.reload}>Refresh Media</button>{viewing&&<Dialog title={viewing.exercise_name||'Conversation Media'} className="attachment-viewer" onClose={()=>{if(!deleting&&!mutation.busy)setViewing(null);}}><AttachmentPreview item={viewing}/><ErrorNote message={error||mutation.error}/>{viewing.owned&&!viewing.shared_at&&<><p>This file is private until you send it to the conversation.</p><button className="button primary" disabled={!canSend||deleting||mutation.busy} onClick={async()=>{if(await mutation.run('attachment.share',{id:viewing.id})){setViewing(null);resource.reload();}}}>{mutation.busy?'Sending…':'Send to Conversation'}</button>{!canSend&&<p>Your coaching service must be active to send media.</p>}</>}{viewing.owned&&<button className="button" disabled={deleting||mutation.busy} onClick={()=>setConfirmRemove(true)}><Trash2 size={18}/>Remove File</button>}</Dialog>}{viewing&&confirmRemove&&<Dialog title="Remove this file?" onClose={()=>{if(!deleting)setConfirmRemove(false);}}><p>It will no longer be available in Gymaf. This cannot erase a copy another participant already saved.</p><ErrorNote message={error}/><button className="button primary" disabled={deleting} onClick={()=>void remove()}>{deleting?'Removing…':'Remove File Permanently'}</button><button className="button" disabled={deleting} onClick={()=>setConfirmRemove(false)}>Keep File</button></Dialog>}</section>;
}
