"use client";
import { useState } from 'react';
import { MemberMediaView, SelectedPhoto } from './member-media';
import type { MemberMedia } from '@/shared/gymaf/contracts';
import { MemberViews, preferenceDefaults } from './member-views';
import { TrainingLibraryView } from "./training-library";
import { ExerciseHistoryView } from "./exercise-history";
import { FeedbackView, FlagEditor } from './session-feedback';
import { SessionSummary } from "./session-summary";
import { SessionView } from './session-view';
import type { Bootstrap, MemberRecord, RelationshipDetail, SessionState } from '@/shared/gymaf/contracts';
import { ClientHome, ProgressView, ProfileOverview, ScheduleView, WorkoutDetailView } from './client-views';
import { Navigation } from './ui';
const profile={id:'visual-client',display_name:'Alex Smith',locale:'en' as const,timezone:'Europe/Sofia',goal:'Increase Muscle Mass',equipment:'Dumbbells, Yoga Mat',availability:'Monday, Wednesday, Friday',revision:1};
const relationship={id:'visual-relationship',workspace_id:'visual-workspace',client_user_id:profile.id,coach_user_id:'visual-coach',state:'active' as const,client_name:profile.display_name,coach_name:'Your Coach'};
const account:Bootstrap={user:profile,relationships:[relationship],workspaces:[],operator:false,requires_mfa:false,local_mode:true,notifications:[]};
const prescription={id:'visual-workout',title:'Morning Yoga Flow',dayOffset:0,exercises:[{id:'visual-exercise',name:'Modified Plyo Push-Up',instructions:'Follow the instructions provided by your coach.',sets:[{reps:15,loadKg:null,durationSeconds:60,distanceM:null,restSeconds:30}]}]};
const today=new Date().toLocaleDateString('en-CA',{timeZone:'Europe/Sofia'});
const initial:RelationshipDetail={relationship,client:profile,workouts:[{id:'visual-scheduled',relationship_id:relationship.id,scheduled_date:today,timezone:profile.timezone,state:'assigned',revision:1,prescription}],sessions:[],check_ins:[],entitlements:[],can_train:true};
export const memberReviewViews=['settings','location','equipment','injury','event','weight','log-weight','app-settings','workout-settings','tones','instructions'];
const memberPaths:Record<string,string[]>={settings:['settings'],location:['settings','location'],equipment:['settings','equipment','visual-location'],injury:['settings','injury'],event:['profile','event'],weight:['progress','weight'],'log-weight':['progress','log-weight'],'app-settings':['settings','app'],'workout-settings':['settings','workout'],tones:['settings','tones'],instructions:['settings','instructions']};
function MemberReview({view}:{view:string}){
 const [path,setPath]=useState(memberPaths[view]),[busy,setBusy]=useState(false);
 const [records,setRecords]=useState<MemberRecord[]>([{id:'visual-location',kind:'location',data:{name:'Home',type:'Home',equipment:['Dumbbell','Yoga Mat']},revision:1,updated_at:today+'T08:00:00Z'},{id:'visual-preferences',kind:'preferences',data:preferenceDefaults,revision:1,updated_at:today+'T08:00:00Z'}]);
 const navigate=(href:string)=>setPath(href.split('?')[0].split('/').filter(Boolean).slice(1));
 return <div className="gymaf-connected gymaf-client" onClickCapture={event=>{if((event.target as HTMLElement).closest('[data-member-navigation-blocked="true"]')){event.preventDefault();return;}const anchor=(event.target as HTMLElement).closest('a');const href=anchor?.getAttribute('href');if(href?.startsWith('/app/settings')||href?.startsWith('/app/progress')||href?.startsWith('/app/profile/event')){event.preventDefault();navigate(href);} }}><main id="main" className="app-shell"><MemberViews key={path.join('/')} account={account} path={path} query="" records={records} busy={busy} navigate={navigate} save={async(kind,data,record)=>{setBusy(true);await new Promise(resolve=>setTimeout(resolve,1200));const id=record?.id||crypto.randomUUID();setRecords(previous=>[...previous.filter(r=>r.id!==id),{id,kind,data,revision:(record?.revision||0)+1,updated_at:new Date().toISOString()}]);setBusy(false);return id;}} remove={async record=>{setRecords(previous=>previous.filter(r=>r.id!==record.id));return true;}}/></main></div>;
}

function MediaReview({view}:{view:string}){
 const kind=view==='cover-photos'?'cover':view==='avatar-photos'?'avatar':'progress';
 const [items,setItems]=useState<MemberMedia[]>([]),[files,setFiles]=useState<Record<string,File>>({});
 return <div className="gymaf-connected gymaf-client"><main id="main" className="app-shell"><MemberMediaView kind={kind} items={items} today={today} draftKey={'visual:'+view} back="/design-review?view=progress&frame=1" onSaved={()=>{}} onDone={()=>{}} onSelect={async item=>{setItems(current=>current.map(row=>row.kind===kind?{...row,selected_at:row.id===item.id?new Date().toISOString():null}:row));}} onUpload={async(file,id,photoView,date)=>{await new Promise(resolve=>setTimeout(resolve,350));if(view==='photo-error'&&photoView!=='front')throw new Error('The photo upload could not be confirmed. Retry Save.');setFiles(current=>({...current,[id]:file}));setItems(current=>[...current.filter(item=>item.id!==id),{id,kind,view:photoView,taken_on:date,created_at:new Date().toISOString()}]);}} onRemove={async item=>{setItems(current=>current.filter(row=>row.id!==item.id));}} renderPhoto={item=>files[item.id]?<SelectedPhoto file={files[item.id]}/>:null}/></main>{kind==='progress'&&<Navigation area="app" active="history" locale="en"/>}</div>;
}

/** Development-only, presentation-level fixtures. Never imported by ConnectedApp or its API hooks. */
export function DesignReview({view}:{view:string}) {
 const [feedback,setFeedback]=useState<import('@/shared/gymaf/contracts').SessionFeedback>({sessionId:'visual-session',editable:true,canSubmit:true,coachName:'Your Coach',revision:0,data:{rating:null,difficulty:null,body:'',flags:[]},sharedRevision:null,sharedAt:null});
 const [feedbackBusy,setFeedbackBusy]=useState(false),[feedbackDirty,setFeedbackDirty]=useState(false),[exitRequest,setExitRequest]=useState(0);
 async function saveFeedback(next:import('@/shared/gymaf/contracts').FeedbackData){setFeedbackBusy(true);await new Promise(resolve=>setTimeout(resolve,400));setFeedback(r=>({...r,revision:r.revision+1,data:next}));setFeedbackBusy(false);return true;}
 const [favorites,setFavorites]=useState<import('@/shared/gymaf/contracts').WorkoutFavorite[]>([]);
 const [data,setData]=useState(initial),[user,setUser]=useState(profile),[sessionState,setSessionState]=useState<SessionState>("in_progress");
 if(['photos','photo-error','cover-photos','avatar-photos'].includes(view))return <MediaReview key={view} view={view}/>;
 if(view==='library')return <div className="gymaf-connected gymaf-client"><TrainingLibraryView data={{...data,workouts:Array.from({length:6},(_,i)=>({...data.workouts[0],id:'visual-scheduled-'+i,prescription:{...prescription,title:['Core and Glutes Burner','Full Body Strength','Upper Body Power Hour','Quick Core Crusher','Morning Yoga Flow','Conditioning'][i]}}))}} query="" favorites={favorites} onFavorite={(w,favorite)=>setFavorites(rows=>[...rows.filter(f=>f.scheduled_id!==w.id),{scheduled_id:w.id,favorite,revision:1}])}/></div>;
 if(view==='summary'||view==='feedback')return <div className="gymaf-connected gymaf-client"><SessionSummary initialTab={view==='feedback'?'Feedback':'Summary'} feedbackDirty={feedbackDirty} onDirtyExit={()=>setExitRequest(n=>n+1)} feedback={<FeedbackView draftKey="visual:summary" exitRequest={exitRequest} onLeave={()=>{setFeedbackDirty(false);setExitRequest(0);}} record={feedback} exercises={prescription.exercises} busy={feedbackBusy} onDirty={setFeedbackDirty} onSave={saveFeedback} onSubmit={async next=>{await saveFeedback(next);setFeedback(r=>({...r,sharedRevision:r.revision,sharedAt:new Date().toISOString()}));return true;}}/>} detail={{editable:false,sets:[],session:{id:'visual-session',relationship_id:relationship.id,scheduled_workout_id:'visual-scheduled',prescription,state:'completed',revision:1,started_at:today+'T08:00:00Z',running_since:null,elapsed_seconds:1131,completed_at:today+'T08:18:51Z'}}} back='/design-review?view=home&frame=1' renderSets={()=> <p>No set values in this synthetic presentation.</p>}/></div>;
 if(memberReviewViews.includes(view))return <MemberReview key={view} view={view}/>;
 return <div className="gymaf-connected gymaf-client"><main id="main" className={`app-shell connected-route-${view==='home'?'home':view==='progress'?'history':view==='workout'?'workouts':view==='player'?'sessions':view} ${view==='home'?'home-page':''}`}>
 {view==='home'?<ClientHome account={{...account,user}} data={data} query=""/>:view==='progress'?<ProgressView data={data} query="" user={user} onGoal={async goal=>{setUser({...user,goal});return true;}}/>:view==='schedule'?<ScheduleView data={data} query="" onMove={async(w,date)=>{setData({...data,workouts:data.workouts.map(x=>x.id===w.id?{...x,scheduled_date:date}:x)});return true;}}/>:view==='player'?<SessionView renderFlag={(id,close)=><FlagEditor draftKey={'visual:player:'+id} exercise={{...prescription.exercises[0],id,name:id==='visual-exercise'?'Modified Plyo Push-Up':'Standing Calf Raise'}} flag={feedback.data?.flags.find(f=>f.exerciseId===id)} busy={feedbackBusy} onClose={close} onSave={flag=>saveFeedback({...feedback.data!,flags:[...feedback.data!.flags.filter(f=>f.exerciseId!==id),...(flag?[flag]:[])]})}/>} preferences={{countdown:true,vibration:true,tone:'Beep',instructions:'Periodic'}} detail={{editable:sessionState==='in_progress'||sessionState==='paused',sets:[],session:{id:'visual-session',relationship_id:relationship.id,scheduled_workout_id:'visual-scheduled',prescription:{...prescription,exercises:[...prescription.exercises,{...prescription.exercises[0],id:'visual-exercise-2',name:'Standing Calf Raise'}]},state:sessionState,revision:1,started_at:today+'T08:00:00Z',running_since:null,elapsed_seconds:19,completed_at:null}}} elapsed={19} back='/design-review?view=home&frame=1' dirty={false} busy={false} onTransition={setSessionState} renderHistory={()=> <ExerciseHistoryView history={{as_of:today+'T08:00:00Z',entries:[],has_more:false}}/>} renderSets={()=> <p>Set entry uses the connected server in the account view. This visual page makes no server requests.</p>}/>:view==='profile'?<ProfileOverview account={{...account,user}} data={data} query=""/>:<WorkoutDetailView workout={data.workouts[0]} query=""><button className="button primary full" disabled title="Starting a workout requires a connected account">Start</button></WorkoutDetailView>}
 </main>{view!=='workout'&&view!=='schedule'&&view!=='player'&&<Navigation area="app" active={view==='home'?'':view==='progress'?'history':view} locale="en"/>}</div>;
}
