"use client";
import Link from 'next/link';
import { useBackend } from '@/lib/backend/context';
import { Photo } from '@/components/primitives';
import { media } from '@/lib/data';
import { useRouter } from 'next/navigation';
import { useEffect, useRef, useState, useSyncExternalStore } from 'react';
import { Check, ChevronLeft, Copy, QrCode, Share2, UserPlus, X } from 'lucide-react';
import { api, invitationToken } from './api';
import { Dialog, ErrorNote, Pending, useCommand, useResource } from './ui';
import { InitialAvatar } from './client-views';

export type FriendData={friends:{id:string;name:string;self:boolean;workouts:number}[];weekStartsAt:string;timezone:string;invitations?:{id:string;expiresAt:string}[]};
const subscribeHash=(callback:()=>void)=>{window.addEventListener('hashchange',callback);return()=>window.removeEventListener('hashchange',callback);};
const hashToken=()=>new URLSearchParams(window.location.hash.slice(1)).get('invite')||'';
function FriendInvitation({token,onAccepted}:{token:string;onAccepted:()=>void}){
 const [data,setData]=useState<{inviterName:string;ownInvitation:boolean;expiresAt:string}|null>(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
 const mutation=useCommand();
 useEffect(()=>{const controller=new AbortController();void api<{inviterName:string;ownInvitation:boolean;expiresAt:string}>('me/friends/invitation',{method:'POST',body:{token},signal:controller.signal}).then(value=>{if(!controller.signal.aborted){setData(value);setError('');}}).catch(failure=>{if(!controller.signal.aborted)setError(failure instanceof Error?failure.message:'Invitation unavailable.');});return()=>controller.abort();},[token,attempt]);
 return <section className="friends-invite"><Link className="icon-button" href="/app/friends" aria-label="Close invitation"><X/></Link><h1>{data?`Connect with ${data.inviterName||'your friend'}`:'Friend invitation'}</h1><p>Accepting shares your display name and weekly completed-workout count with this friend. Your photos, messages, weight and workout details stay private. Either of you can remove the connection.</p><ErrorNote message={error||mutation.error}/>{!data&&!error&&<p role="status">Loading invitation…</p>}{error&&<><Link className="button primary" href="/login" target="_blank" rel="noopener noreferrer">Sign In in a New Tab</Link><p>Keep this invitation open. After signing in, return here and retry.</p><button className="button" onClick={()=>setAttempt(value=>value+1)}>Retry Invitation</button></>}{data&&(data.ownInvitation?<p>This is your own invitation. Share it privately with the person you want to connect with.</p>:<button className="button primary full" disabled={mutation.busy} onClick={async()=>{if(await mutation.run('social.accept',{token}))onAccepted();}}>{mutation.busy?'Connecting…':'Accept Friend Invitation'}</button>)}</section>;
}
export function FriendJoin(){const token=useSyncExternalStore(subscribeHash,hashToken,()=>''),router=useRouter();return <div className="gymaf-connected gymaf-client"><main className="app-shell">{token?<FriendInvitation key={token} token={token} onAccepted={()=>router.replace('/app/friends')}/>:<section className="friends-invite"><h1>Friend invitation</h1><p>Open the complete private invitation link your friend shared with you.</p><Link className="button" href="/app/friends">Open Friends</Link></section>}</main></div>;}
export function Friends({ownerId,inviteView=false,query}:{ownerId:string;inviteView?:boolean;query:string}){
 const template=!!useBackend();
 const token=useSyncExternalStore(subscribeHash,hashToken,()=>''),resource=useResource<FriendData>('me/friends'),mutation=useCommand();
 const [link,setLink]=useState(''),[qr,setQr]=useState(''),[showQr,setShowQr]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false),[removing,setRemoving]=useState<FriendData['friends'][number]|null>(null);
 const generated=useRef('');
 useEffect(()=>{if(!link)return;let alive=true;void import('qrcode').then(module=>module.toDataURL(link,{width:480,margin:3,errorCorrectionLevel:'M'})).then(value=>{if(alive)setQr(value);}).catch(()=>{if(alive)setError('The QR code could not load. Copy the invitation link instead.');});return()=>{alive=false;};},[link]);
 async function create(){setError('');generated.current ||= invitationToken();if(await mutation.run('social.invite',{token:generated.current})){setLink(`${window.location.origin}/friend-invite#invite=${generated.current}`);resource.reload();}}
 async function share(){setError('');try{if(navigator.share)await navigator.share({title:'Connect on Gymaf',text:'Connect privately to compare weekly workouts.',url:link});else{await navigator.clipboard.writeText(link);setCopied(true);}}catch(failure){if(!(failure instanceof DOMException&&failure.name==='AbortError'))setError('Sharing could not open. Select and copy the link below.');}}
 function accepted(){history.replaceState(null,'',window.location.pathname+window.location.search);window.dispatchEvent(new HashChangeEvent('hashchange'));resource.reload();}
 if(token)return <FriendInvitation key={`${ownerId}:${token}`} token={token} onAccepted={accepted}/>;
 if(!resource.data)return <Pending error={resource.error} reload={resource.reload}/>;
 const invitation=<><p>Share a private invitation to compare weekly workouts. When your friend accepts, you both share your display names and completed-workout counts. The link can be used once and expires in seven days.</p><p className="friends-privacy">An invitation adds a friend. It does not grant a paid membership, trial or referral credit.</p><ErrorNote message={error||mutation.error}/>{!link?<button className="button primary" disabled={mutation.busy} onClick={()=>void create()}><UserPlus size={18}/>{mutation.busy?'Creating…':'Create Friend Invitation'}</button>:<><div className="friends-share-actions"><button className="icon-button" onClick={()=>setShowQr(true)} aria-label="Show invitation QR code"><QrCode/></button><button className="button primary" onClick={()=>void share()}><Share2 size={18}/>{copied?'Link Copied':'Share Invitation'}</button></div><label className="form-field">Private invitation link<input readOnly value={link} onFocus={event=>event.target.select()}/></label><button className="button" disabled={mutation.busy} onClick={async()=>{if(await mutation.run('social.revoke',{token:generated.current})){generated.current='';setLink('');setQr('');setCopied(false);resource.reload();}}}>Revoke Link</button></>}{(resource.data.invitations?.length||0)>0&&<section className="friends-active-invites"><h2>Active Invitations</h2><p>You can revoke these links even after leaving this page.</p>{resource.data.invitations?.map((item,index)=><div key={item.id}><p>Invitation {index+1} · Expires {new Date(item.expiresAt).toLocaleString()}</p><button className="button" disabled={mutation.busy} onClick={async()=>{if(await mutation.run('social.revoke-id',{id:item.id})){generated.current='';setLink('');setQr('');resource.reload();}}}>Revoke Invitation {index+1}</button></div>)}</section>}{showQr&&<Dialog title="Your friend invitation" onClose={()=>setShowQr(false)} className="friends-qr">{qr?<img src={qr} width={240} height={240} alt="QR code for this private friend invitation"/>:<p>Preparing QR code…</p>}{/* eslint-disable-line @next/next/no-img-element -- Local generated data URL. */}<p>Only share with the person you want to connect with.</p><button className="button primary full" onClick={()=>void share()}><Copy size={18}/>Share Link</button><ErrorNote message={error}/></Dialog>}</>;
 if(inviteView)return <section className="friends-invite"><Link href={`/app/friends${query}`} className="icon-button" aria-label="Close Invite Friends"><X/></Link><h1>Invite Friends to Gymaf</h1>{invitation}</section>;
 return <section className="friends-page"><header className="native-titlebar"><Link className="icon-button" href={`/app/profile${query}`} aria-label="Back"><ChevronLeft/></Link><h1>Friends</h1><Link className="icon-button" href={`/app/friends/invite${query}`} aria-label="Invite Friends"><UserPlus/></Link></header><div className={template?"friends-card":"friends-introduction"}>{template&&<Photo crop={media.friends} alt="Friends training together"/>}<div><h2>Let your friends pull you forward.</h2><p>Share your weekly workout count with people you choose.</p><Link className="button primary" href={`/app/friends/invite${query}`}>Invite Friends</Link></div></div><section className="friends-leaderboard"><h2>Weekly Leaderboard</h2><p className="friends-week">Week of {new Date(resource.data.weekStartsAt).toLocaleDateString('en-US',{timeZone:resource.data.timezone,month:'short',day:'numeric'})} · {resource.data.timezone}</p><ErrorNote message={resource.error||mutation.error}/><ol>{resource.data.friends.map((friend,index)=><li key={friend.id}><span className="friend-rank">{index+1}</span><InitialAvatar name={friend.name}/><div><h3>{friend.self?'You':friend.name||'Friend'}</h3><p>{friend.workouts} completed {friend.workouts===1?'workout':'workouts'} this week</p></div>{!friend.self&&<button className="icon-button" aria-label={`Remove ${friend.name||'friend'}`} onClick={()=>setRemoving(friend)}><X size={16}/></button>}</li>)}</ol>{resource.data.friends.length===1&&<p className="friends-privacy">Invite a friend to start comparing your weeks.</p>}<button className="button" onClick={resource.reload}>Refresh Leaderboard</button></section><section className="friends-add"><h2>Add Friends</h2>{invitation}</section>{removing&&<Dialog title="Remove this friend?" onClose={()=>{if(!mutation.busy)setRemoving(null);}}><p>You and {removing.name||'this friend'} will stop seeing each other’s weekly workout count.</p><ErrorNote message={mutation.error}/><button className="button primary" disabled={mutation.busy} onClick={()=>setRemoving(null)}>Keep Friend</button><button className="button" disabled={mutation.busy} onClick={async()=>{if(await mutation.run('social.remove',{id:removing.id})){setRemoving(null);resource.reload();}}}><Check size={18}/>Remove Friend</button></Dialog>}</section>;
}
