"use client";
import { useEffect, useRef, useState, type CSSProperties } from 'react';
import { ChevronRight, Dumbbell, Ellipsis, Flag, Star } from 'lucide-react';
import type { ExerciseFlag, FeedbackData, PlanExercise, SessionFeedback } from '@/shared/gymaf/contracts';
import { Dialog, Empty, ErrorNote, Pending, useCommand, useResource } from './ui';
import { api } from './api';
import { flagReasons } from '@/shared/gymaf/validation';
import { feedbackDraft, keepFeedbackDraft, forgetFeedbackDraft, flagDraft, keepFlagDraft, forgetFlagDraft } from './feedback-drafts';

const empty:FeedbackData={rating:null,difficulty:null,body:'',flags:[]};
const difficultyLabels=['Too Easy','Easy','Just Right','Hard','Too Hard'];

export function FlagEditor({exercise,flag,busy,error,onSave,onClose,draftKey,onDraft,onReload}:{exercise:PlanExercise;flag?:ExerciseFlag;busy:boolean;error?:string;onSave:(flag:ExerciseFlag|null)=>Promise<boolean>;onClose:()=>void;draftKey?:string;onDraft?:()=>void;onReload?:()=>void}) {
  const recovered=draftKey?flagDraft(draftKey):undefined;
  const [reasons,setReasons]=useState(recovered?.reasons||flag?.reasons||[]),[comment,setComment]=useState(recovered?.comment??flag?.comment??''),[discard,setDiscard]=useState(false);
  const dirty=JSON.stringify({reasons,comment})!==JSON.stringify({reasons:flag?.reasons||[],comment:flag?.comment||''});
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  function close(){if(busy)return;if(dirty)setDiscard(true);else onClose();}
  function remember(nextReasons:ExerciseFlag['reasons'],nextComment:string){if(draftKey)keepFlagDraft(draftKey,{exerciseId:exercise.id,reasons:nextReasons,comment:nextComment});onDraft?.();}
  function dismiss(){if(draftKey)forgetFlagDraft(draftKey);onClose();}
  return <Dialog title="Flag" className="connected-flag-dialog" onClose={close}><h3>{exercise.name}</h3><div className="flag-reasons" role="group" aria-label="Reasons for flagging">{flagReasons.map(reason=><button type="button" key={reason} disabled={busy} aria-pressed={reasons.includes(reason)} onClick={()=>{const next=reasons.includes(reason)?reasons.filter(r=>r!==reason):[...reasons,reason];setReasons(next);remember(next,comment);}}>{reason}</button>)}</div><label className="flag-comment"><span className="sr-only">Flag comment</span><textarea placeholder="Additional Comments (Optional)" maxLength={1000} value={comment} disabled={busy} onChange={event=>{setComment(event.target.value);remember(reasons,event.target.value);}}/></label><ErrorNote message={error}/>{error&&onReload&&<button className="button" disabled={busy} onClick={onReload}>Reload Saved Flag</button>}{discard?<div className="flag-discard"><p>Discard changes to this flag?</p><button className="button" onClick={()=>setDiscard(false)}>Keep Editing</button><button className="button" onClick={dismiss}>Discard</button></div>:<><button className="button primary full" disabled={busy||!reasons.length} onClick={async()=>{if(await onSave({exerciseId:exercise.id,reasons,comment}))dismiss();}}>{busy?'Saving…':'Next'}</button><button className="flag-remove" disabled={busy||!flag} onClick={async()=>{if(await onSave(null))dismiss();}}>Remove Flag</button></>}</Dialog>;
}

type ViewProps={record:SessionFeedback;exercises:PlanExercise[];busy?:boolean;error?:string;onSave:(data:FeedbackData)=>Promise<boolean>;onSubmit:(data:FeedbackData,dirty:boolean)=>Promise<boolean>;onDirty?:(dirty:boolean)=>void;onReload?:()=>void;draftKey?:string;exitRequest?:number;onLeave?:()=>void};
export function FeedbackView({record,exercises,busy=false,error,onSave,onSubmit,onDirty,onReload,draftKey,exitRequest=0,onLeave}:ViewProps){
  const [data,setData]=useState((draftKey?feedbackDraft(draftKey)?.data:null)||record.data||empty),[saved,setSaved]=useState(record.data||empty),[flagId,setFlagId]=useState(''),[choose,setChoose]=useState(false),[notice,setNotice]=useState(''),[handledExit,setHandledExit]=useState(exitRequest);
  const dirty=JSON.stringify(data)!==JSON.stringify(saved),editable=record.editable;
  const callback=useRef(onDirty);
  useEffect(()=>{callback.current=onDirty;},[onDirty]);
  useEffect(()=>{callback.current?.(dirty);const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  useEffect(()=>()=>callback.current?.(false),[]);
  function change(next:FeedbackData){setData(next);setNotice('');if(draftKey)keepFeedbackDraft(draftKey,record,next);}
  async function save(next=data){if(!await onSave(next))return false;if(draftKey)forgetFeedbackDraft(draftKey);setData(next);setSaved(next);setNotice('Draft saved. Only you can see these changes.');return true;}
  const exercise=exercises.find(e=>e.id===flagId);
  const hasContent=data.rating!==null||data.difficulty!==null||!!data.body.trim()||!!data.flags.length;
  if(!editable&&!record.data)return <Empty>No workout feedback has been sent yet.</Empty>;
  return <div className="connected-feedback">
    {editable&&<details className="feedback-menu"><summary className="icon-button" aria-label="Workout feedback options"><Ellipsis/></summary><div><button disabled={busy||!dirty} onClick={()=>void save()}>Save Draft</button><p>Drafts stay private until you press Send.</p></div></details>}
    <section className="feedback-card"><h2>How was your workout?</h2><div className="feedback-stars" role="group" aria-label="Workout rating">{[1,2,3,4,5].map(n=><button key={n} aria-label={`${n} ${n===1?'star':'stars'}`} aria-pressed={data.rating===n} disabled={!editable||busy} onClick={()=>change({...data,rating:data.rating===n?null:n})}><Star fill={(data.rating||0)>=n?'currentColor':'none'}/></button>)}</div><label className="feedback-difficulty"><span>How tough was it?</span><output>{data.difficulty?difficultyLabels[data.difficulty-1]:'Choose difficulty'}</output><input style={{'--feedback-fill':`${((data.difficulty||3)-1)*25}%`} as CSSProperties} type="range" min={1} max={5} step={1} value={data.difficulty||3} aria-label="Workout difficulty" aria-valuetext={data.difficulty?difficultyLabels[data.difficulty-1]:'Not selected'} disabled={!editable||busy} onChange={e=>change({...data,difficulty:Number(e.target.value)})} onPointerUp={e=>{if(editable&&!busy)change({...data,difficulty:Number(e.currentTarget.value)});}} onKeyDown={e=>{if(editable&&!busy&&(e.key==='Enter'||e.key===' ')){e.preventDefault();change({...data,difficulty:Number(e.currentTarget.value)});}}}/></label><label className="feedback-comment"><span className="sr-only">Workout feedback</span><textarea placeholder="Anything else you'd like your coach to know?" maxLength={2000} readOnly={!editable} disabled={busy} value={data.body} onChange={e=>change({...data,body:e.target.value})}/></label>
      {editable&&<><button className="button primary full feedback-send" disabled={busy||!record.canSubmit||!hasContent||(!dirty&&record.sharedRevision===record.revision)} onClick={async()=>{if(await onSubmit(data,dirty)){setSaved(data);setNotice('Feedback sent to '+record.coachName+'.');}}}>{busy?'Saving…':record.sharedRevision?'Send Updated Feedback':'Send to '+record.coachName}</button></>}
      {record.sharedAt&&<p className="feedback-status">Sent {new Date(record.sharedAt).toLocaleString()}{editable&&(dirty||record.revision!==record.sharedRevision)?' · Changes not sent':''}</p>}
      {editable&&!record.canSubmit&&<p className="feedback-status">You can save a private draft. Sending requires a finished workout and an active coaching relationship.</p>}
      <p className="feedback-status" role="status">{notice||(dirty?'Unsaved changes. Save your draft or send your feedback.':'')}</p><ErrorNote message={error}/>{error&&onReload&&<button className="button" disabled={busy} onClick={onReload}>Reload Saved Feedback</button>}
    </section>
    <section className="feedback-card feedback-flags"><h2>Flagged Exercises <Flag size={17}/></h2>{data.flags.map(f=><div className="feedback-flag" key={f.exerciseId}><span className="exercise-glyph"><Dumbbell/></span><div><b>{exercises.find(e=>e.id===f.exerciseId)?.name||'Exercise'}</b><p>{f.reasons.join(', ')}</p>{f.comment&&<p>{f.comment}</p>}</div>{editable&&<button disabled={busy} onClick={()=>setFlagId(f.exerciseId)}>Edit</button>}</div>)}{!data.flags.length&&<p className="feedback-status">No movements flagged.</p>}{editable&&<button className="feedback-add-flag" disabled={busy} onClick={()=>setChoose(true)}>Flag More Movements <ChevronRight size={18}/></button>}</section>
    {choose&&<Dialog title="Flag a Movement" onClose={()=>setChoose(false)}><div className="player-overview">{exercises.map(e=><button key={e.id} onClick={()=>{setChoose(false);setFlagId(e.id);}}><span>{e.name}</span><ChevronRight/></button>)}</div></Dialog>}
    {exercise&&<FlagEditor draftKey={draftKey?draftKey+':'+exercise.id:undefined} onDraft={()=>{if(draftKey)keepFeedbackDraft(draftKey,record,data);}} exercise={exercise} flag={data.flags.find(f=>f.exerciseId===exercise.id)} busy={busy} error={error} onClose={()=>setFlagId('')} onSave={f=>save({...data,flags:[...data.flags.filter(item=>item.exerciseId!==exercise.id),...(f?[f]:[])]})}/>}
    {exitRequest>handledExit&&<Dialog title="Unsaved Feedback" onClose={()=>{if(!busy)setHandledExit(exitRequest);}}><p>Save your private draft before leaving, or discard your changes.</p><ErrorNote message={error}/><button className="button primary" disabled={busy} onClick={async()=>{if(await save()){setHandledExit(exitRequest);onLeave?.();}}}>{busy?'Saving…':'Save Draft and Leave'}</button><button className="button" disabled={busy} onClick={()=>setHandledExit(exitRequest)}>Keep Editing</button><button className="button" disabled={busy} onClick={()=>{if(draftKey)forgetFeedbackDraft(draftKey);setData(saved);setHandledExit(exitRequest);onLeave?.();}}>Discard and Leave</button></Dialog>}
  </div>;
}

export function SessionFeedbackPanel({sessionId,exercises,onDirty,ownerId,exitRequest,onLeave}:{sessionId:string;exercises:PlanExercise[];onDirty?:(dirty:boolean)=>void;ownerId:string;exitRequest?:number;onLeave?:()=>void}){
  const resource=useResource<SessionFeedback>(`workout-sessions/${sessionId}/feedback`),mutation=useCommand();
  const [generation,setGeneration]=useState(0),[discard,setDiscard]=useState(false),[dirty,setDirty]=useState(false),[submitting,setSubmitting]=useState(false),[refreshing,setRefreshing]=useState(false),[refreshError,setRefreshError]=useState('');
  const lock=useRef(false);
  if(!resource.data)return <Pending error={resource.error} reload={resource.reload}/>;
  const draftKey=ownerId+':'+sessionId,recovered=feedbackDraft(draftKey),record=recovered?{...resource.data,data:recovered.record.data,revision:recovered.record.revision}:resource.data;
  async function persist(data:FeedbackData){const ack=await mutation.run('feedback.save',{sessionId,revision:record.revision,data});if(ack){forgetFeedbackDraft(draftKey);resource.update(r=>({...r,data,revision:ack.revision!}));}return ack;}
  async function reload(){setRefreshing(true);setRefreshError('');try{const latest=await api<SessionFeedback>(`workout-sessions/${sessionId}/feedback`);forgetFeedbackDraft(draftKey);resource.update(()=>latest);mutation.clearError();setGeneration(g=>g+1);setDiscard(false);}catch(error){setRefreshError(error instanceof Error?error.message:'Could not reload feedback.');}finally{setRefreshing(false);}}
  return <><FeedbackView key={`${sessionId}:${generation}`} draftKey={draftKey} exitRequest={exitRequest} onLeave={onLeave} record={record} exercises={exercises} busy={mutation.busy||submitting||refreshing} error={refreshError||resource.error||mutation.error} onDirty={value=>{setDirty(value);onDirty?.(value);}} onReload={()=>dirty?setDiscard(true):void reload()} onSave={async data=>!!await persist(data)} onSubmit={async(data)=>{
    if(lock.current)return false;lock.current=true;setSubmitting(true);
    try {let revision=record.revision;if(JSON.stringify(data)!==JSON.stringify(record.data)||!revision){const ack=await persist(data);if(!ack)return false;revision=ack.revision!;}
      const ack=await mutation.run('feedback.submit',{sessionId,revision});if(!ack)return false;forgetFeedbackDraft(draftKey);resource.reload();return true;
    }finally{lock.current=false;setSubmitting(false);}
  }}/>{discard&&<Dialog title="Reload Saved Feedback" onClose={()=>{if(!refreshing)setDiscard(false);}}><p>This replaces your unsaved changes with the saved draft.</p><ErrorNote message={refreshError}/><button className="button primary" disabled={refreshing} onClick={()=>void reload()}>{refreshing?'Loading…':'Discard Changes and Reload'}</button><button className="button" disabled={refreshing} onClick={()=>setDiscard(false)}>Keep Editing</button></Dialog>}</>;
}

export function SessionFlagPanel({sessionId,exercise,onClose,ownerId}:{sessionId:string;exercise:PlanExercise;onClose:()=>void;ownerId:string}){
  const resource=useResource<SessionFeedback>(`workout-sessions/${sessionId}/feedback`),mutation=useCommand();
  const [generation,setGeneration]=useState(0),[reloadPrompt,setReloadPrompt]=useState(false),[refreshing,setRefreshing]=useState(false),[refreshError,setRefreshError]=useState('');
  if(!resource.data)return <Dialog title="Flag" className="connected-flag-dialog" onClose={onClose}><Pending error={resource.error} reload={resource.reload}/></Dialog>;
  const draftKey=ownerId+':'+sessionId,recovered=feedbackDraft(draftKey),record=recovered?{...resource.data,data:recovered.record.data,revision:recovered.record.revision}:resource.data;
  if(!record.editable||!record.data)return <Dialog title="Flag" onClose={onClose}><p>Only the member can edit movement flags.</p></Dialog>;
  return <><FlagEditor key={generation} draftKey={draftKey+':'+exercise.id} onDraft={()=>keepFeedbackDraft(draftKey,record,recovered?.data||record.data!)} exercise={exercise} flag={record.data.flags.find(f=>f.exerciseId===exercise.id)} busy={mutation.busy||refreshing} error={refreshError||mutation.error||resource.error} onReload={()=>setReloadPrompt(true)} onClose={onClose} onSave={async flag=>{const ack=await mutation.run('feedback.save',{sessionId,revision:record.revision,data:{...(recovered?.data||record.data),flags:[...(recovered?.data||record.data)!.flags.filter(f=>f.exerciseId!==exercise.id),...(flag?[flag]:[])]}});if(ack)forgetFeedbackDraft(draftKey);return !!ack;}}/>{reloadPrompt&&<Dialog title="Reload Saved Flag" onClose={()=>{if(!refreshing)setReloadPrompt(false);}}><p>This replaces your unsaved flag with the saved version. Keep editing to retain your current text.</p><ErrorNote message={refreshError}/><button className="button primary" disabled={refreshing} onClick={async()=>{setRefreshing(true);setRefreshError('');try{const latest=await api<SessionFeedback>(`workout-sessions/${sessionId}/feedback`);forgetFeedbackDraft(draftKey);resource.update(()=>latest);mutation.clearError();setGeneration(g=>g+1);setReloadPrompt(false);}catch(error){setRefreshError(error instanceof Error?error.message:'Could not reload flag.');}finally{setRefreshing(false);}}}>{refreshing?'Loading…':'Discard Changes and Reload'}</button><button className="button" disabled={refreshing} onClick={()=>setReloadPrompt(false)}>Keep Editing</button></Dialog>}</>;
}
